config/routes.rb
Mantragram::Application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations}
  resources  :users
  resources  :mantras
  resources  :styles, only: [:edit, :update]

  root 'static_pages#home'

  match '/remove_image/:id', to: 'mantras#remove_image', via: 'post', as: 'remove_image'
  match '/send_now/:id',     to: 'mantras#send_now',     via: 'post', as: 'send_now'
  match '/reset_style',      to: 'users#reset_style',    via: 'post', as: 'reset_style'

  match '/queue' => DelayedJobWeb, anchor: false, via: [:get, :post]

end

app/models/mantra.rb
class Mantra < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image
  validates_attachment_content_type :image, content_type: ['image/jpeg', 'image/gif', 'image/png']
  validates_attachment_size :image, less_than: 5.megabytes
  scope :active, -> { where(status: 'Active') }

  def deliver
    UserMailer.mantra_message(self)
  end

end

app/models/style.rb
class Style < ActiveRecord::Base
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  include Carriers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :mantras
  has_one :style
  before_validation :sanitize_mobile_number
  before_create :set_style
  before_create :activate
  before_create :generate_reference
  before_save :set_smtp_address
  before_destroy :erase_mantras
  validates :mobile_number, numericality: { only_integer: true }, presence: true, uniqueness: true, length: { is: 10 }
  validates :email, uniqueness: { case_sensitive: false }, allow_nil: true, allow_blank: true
  validates :smtp_address, uniqueness: { case_sensitive: false }
  validates :carrier, presence: true

  def email_required?
    false
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if mobile_number = conditions.delete(:mobile_number)
      where(conditions).where(["mobile_number = :value", { :value => mobile_number }]).first
    else
      where(conditions).first
    end
  end

  def reset_style
    self.style.destroy
    Style.create(user_id: self.id)
  end

  private

  def sanitize_mobile_number
    self.mobile_number = mobile_number.gsub(/[^0-9]/, '') if attribute_present?('mobile_number')
  end

  def set_style
    Style.create(user_id: self.id)
  end

  def activate
    self.status = 'Active'
  end

  def generate_reference
    self.reference = "#{DateTime.now.to_i}#{SecureRandom.hex(3)}"
  end

  def set_smtp_address
    self.smtp_address = (self.mobile_number + domain_name(self.carrier)) if self.carrier_changed?
  end

  def erase_mantras
    self.mantras.each { |m| m.destroy }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:mobile_number, :carrier, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:mobile_number, :carrier, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:mobile_number, :carrier, :email, :password, :current_password) }
  end

end

app/controllers/mantras_controller.rb
class MantrasController < ApplicationController

  def new
    @mantra = Mantra.new
  end

  def create
    @mantra = current_user.mantras.create(mantra_params.merge(status: 'Active'))
    if @mantra.save
      flash[:success] = 'Nicely done. Your mantra has been saved.'
      redirect_to current_user
    else
      flash[:warning] = 'Whoops, something is missing from your mantra.'
      redirect_to current_user
    end
  end

  def edit
    @mantra = Mantra.find(params[:id])
  end

  def update
    @mantra = Mantra.find(params[:id])
    if @mantra.update(mantra_params)
      respond_to do |format|
        format.html { flash[:success] = 'Your mantra has been updated.'
                      redirect_to current_user }
        format.json { respond_with_bip @mantra }
      end
    else
      flash[:warning] = 'Whoops, something is missing. Try again.'
      redirect_to current_user
    end
  end

  def remove_image
    @mantra = Mantra.find(params[:id])
    @mantra.update(image: nil)
    redirect_to current_user
  end

  def destroy
    @mantra = Mantra.find(params[:id])
    if @mantra.update(status: 'Erased')
      flash[:success] = 'All set. The mantra has been removed.'
      redirect_to current_user
    end
  end

  def send_now
    Mantra.find(params[:id]).deliver
    flash[:success] = 'Success. Your Mantra is on its way.'
    redirect_to current_user
  end

  private

  def mantra_params
    params.require(:mantra).permit(:user_id, :title, :description, :schedule, :image)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      flash[:success] = 'Got it. Your password has been updated.'
      sign_in resource_name, resource, bypass: true
      redirect_to user_path(resource)
    else
      clean_up_passwords resource
      flash[:danger] = 'Whoops. That was the incorrect current password.'
      redirect_to user_path(resource)
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @user = User.new
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController

  def edit
    @style = current_user.style
  end

  def update
    if current_user.style.update(style_params)
      flash[:success] = 'Looks great. Your profile has been updated.'
      redirect_to user_path(current_user)
    else
      flash[:warning] = 'Whoops. Looks like something went wrong.'
      redirect_to user_path(current_user)
    end
  end

  private

  def style_params
    params.require(:style).permit(:background, :card_title, :card_title_hover, :card_background, :heading,
      :send_mantra, :send_mantra_hover, :delete_mantra, :delete_mantra_hover, :create_button, :navbar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      respond_to do |format|
        format.html { flash[:success] = 'Awesome, your profile has been updated.'
                      redirect_to current_user }
        format.json { respond_with_bip @user }
      end
    else
      flash[:warning] = 'Whoops, something went wrong. Try again.'
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.update(status: 'Disabled')
      flash[:warning] = 'Your account has been disabled.'
      redirect_to root_path
    end
  end

  def reset_style
    current_user.reset_style
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :carrier, :mobile_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_path
    request.env['PATH_INFO']
  end

end

app/helpers/users_helper.rb
module UsersHelper
  include Carriers

  def carrier_options
    [
      ['Select Carrier', nil],
    ].concat(carrier_names)
  end

  def button_style_options
    [
      ['Blue', 'primary'],
      ['Green', 'success'],
      ['Orange', 'warning'],
      ['Red', 'danger'],
      ['Teal', 'info'],
      ['White', 'default'],
      ['None', 'link']
    ]
  end

end

app/views/layouts/_header.html.erb
<nav class='navbar navbar-default navbar-fixed-top' role='navigation'>
  <div class='container'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#header-menu'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to icon('fa fa-sun-o', 'Mantragram'), root_path, class: 'navbar-brand' %>
    </div>
    <div class='collapse navbar-collapse' id='header-menu'>
      <% if current_user %>
        <ul class='nav navbar-nav pull-right'>
          <li><%= link_to icon('fa fa-user'), user_path(current_user) %></li>
          <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      <% else %>
        <%= form_for User.new, :url => session_path(:user), :html => {:class=> 'navbar-form navbar-right'} do |f| -%>
          <%= f.text_field :mobile_number, autofocus: true, placeholder: 'Mobile Number', class: 'form-control' %>
          <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
          <%= f.submit 'Sign in', class: 'btn btn-default' %>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0, user-scalable=no'>
  <title>Mantragram</title>
  <%= favicon_link_tag 'https://s3-us-west-2.amazonaws.com/mantragram/mantragram_favicon.ico' %>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= content_for :head %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <% flash.each do |key, value| %>
      <% key = :success if key == :notice %>
      <% key = :warning if key == :alert %>
      <% unless value == '' %>
        <div class='alert alert-<%= key %>'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= value %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/static_pages/_call_to_action.html.erb
<div class='row'>
  <div class='col-md-6'>
    <h2>Keep your mantra in focus</h2>
    <p class='lead'>
      Receive text messages with your mantra or a picture to remind you.
      Scheduled by you or sent at random.
    </p>
  </div>

  <div class='col-md-6'>
    <h2>Sign up today</h2>
    <div class='outer'>
      <div class='inner'>
        <%= form_for User.new, as: :user, url: registration_path(:user) do |f| %>
          <%= devise_error_messages! unless current_path == root_path %>
          <div class='form-group'>
            <%= f.label :mobile_number, 'Mobile Number' %>
            <%= f.text_field :mobile_number, class: 'form-control', autofocus: true, placeholder: '321-555-1234' %>
          </div>
          <div class='form-group'>
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: 'off', placeholder: '******', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= f.label :carrier, 'Select your Carrier' %>
            <%= f.select :carrier, carrier_options, {}, { class: 'form-control' } %>
          </div>
          <%= button_tag type: :submit, class: 'btn btn-primary' do %>
            <%= icon('fa fa-check', 'Sign up') %>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= link_to 'Sign in', new_user_session_path %>
  </div>
</div>

app/views/static_pages/home.html.erb
<%= render 'call_to_action' %>

app/views/users/_edit_password_form.html.erb
<div class='row hidden'>
  <div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'>
    <%= form_for(@user, as: @user, url: registration_path(@user), html: { method: :put }) do |f| %>
      <div class='form-group'>
        <%= f.password_field :current_password, autocomplete: 'off', placeholder: 'Current Password', class: 'form-control input-sm' %>
      </div>
      <div class='form-group'>
        <%= f.password_field :password, autocomplete: 'off', placeholder: 'New Password', class: 'form-control input-sm' %>
      </div>
      <%= button_tag type: :submit, class: 'btn btn-default btn-sm' do %>
        <%= icon('fa fa-check', 'Save') %>
      <% end %>
      <span class='cancel-form'>Cancel</span>
    <% end %>
  </div>
</div>

app/views/users/_edit_style_form.html.erb
<div class='row hidden'>
  <div class='col-lg-8 col-md-11 col-sm-12 col-xs-7'>
    <%= form_for @user.style, html: { class: 'form-horizontal mini-color' } do |f| %>
      <div class='form-group'>
        <%= f.label        :navbar, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :navbar, class: 'form-control input-sm', data: { original: @user.style.navbar } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :background, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :background, class: 'form-control input-sm', data: { original: @user.style.background } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :heading, 'Section heading', class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :heading, class: 'form-control input-sm', data: { original: @user.style.heading } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :card_background, 'Card background', class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :card_background, class: 'form-control input-sm', data: { original: @user.style.card_background } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :card_title, 'Mantra title', class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :card_title, class: 'form-control input-sm', data: { original: @user.style.card_title } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :card_title_hover, 'Mantra title hover', class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :card_title_hover, class: 'form-control input-sm', data: { original: @user.style.card_title_hover } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :send_mantra, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :send_mantra, class: 'form-control input-sm', data: { original: @user.style.send_mantra } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :send_mantra_hover, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :send_mantra_hover, class: 'form-control input-sm', data: { original: @user.style.send_mantra_hover } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :delete_mantra, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :delete_mantra, class: 'form-control input-sm', data: { original: @user.style.delete_mantra } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :delete_mantra_hover, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.text_field :delete_mantra_hover, class: 'form-control input-sm', data: { original: @user.style.delete_mantra_hover } %>
        </div>
        <div class='reset-input col-lg-1 col-md-1 col-sm-1 col-xs-1'>
          <span class='hidden'>Reset</span>
        </div>
      </div>
      <div class='form-group'>
        <%= f.label        :create_button, class: 'col-lg-7 col-md-7 col-sm-7 col-xs-7' %>
        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-4'>
          <%= f.select     :create_button, button_style_options, class: 'form-control input-sm' %>
        </div>
      </div>
      <%= button_tag type: :submit, class: 'btn btn-default btn-sm' do %>
        <%= icon('fa fa-check', 'Save') %>
      <% end %>
      <span class='cancel-form'>Cancel</span>
      <span class='reset-style'>
        <%= link_to 'Default', reset_style_path, method: :post, confirm: 'This will erase all your styles. You sure?' %>
      </span>
    <% end %>
  </div>
</div>

app/views/users/_user_stylesheet.html.erb
<%= content_for :head do %>
  <style>
    body { background: <%= current_user.style.background %>; }
    h4 { color: <%= current_user.style.heading %>; }
    .navbar-default { background: <%= current_user.style.navbar %>; }
    .outer { background: <%= current_user.style.card_background %>; }
    .best_in_place { color: <%= current_user.style.card_title %>; }
    .best_in_place:hover { color: <%= current_user.style.card_title_hover%>; }
    .send-now { color: <%= current_user.style.send_mantra %>; }
    .send-now:hover { color: <%= current_user.style.send_mantra_hover %>; }
    .erase { color: <%= current_user.style.delete_mantra %>; }
    .erase:hover { color: <%= current_user.style.delete_mantra_hover %>; }
  </style>
<% end %>

app/views/users/show.html.erb
<%= render 'user_stylesheet' %>

<div class='row'>
  <div class='col-md-6 col-sm-6 col-xs-12'>
    <h4><%= @user.first_name.present? ? "Hi #{@user.first_name}" : 'My Profile' %></h4>
    <hr style='margin: 0 0 10px 0;'>
    <div class='outer'>
      <div class='inner'>
        <h5 class='muted'><%= best_in_place @user, :first_name, nil: "What's your first name?" %></h5>
        <h5 class='muted'><%= best_in_place @user, :last_name, nil: "What's your last name?" %></h5>
        <h5 class='muted'><%= best_in_place @user, :email, nil: "What's your email?" %></h5>
        <h5 class='muted show-form'><i class='fa fa-key'></i> Change password</h5>
        <%= render 'edit_password_form' %>
        <h5 class='muted show-form'><i class='fa fa-paint-brush fa-flip-horizontal'></i> Change style</h5>
        <%= render 'edit_style_form' %>
      </div>
    </div>
  </div>

  <div class='col-md-6 col-sm-6 col-xs-12'>
    <h4>Create a New Mantra</h4>
    <hr style='margin: 0 0 10px 0;'>
    <div class='outer'>
      <div class='inner'>
        <%= form_for @user.mantras.new, html: { multipart: true } do |f| %>
          <div class='form-group'>
            <%= f.text_field :title, class: 'form-control', placeholder: 'Do something better every day...' %>
          </div>
          <div class='form-group'>
            <%= f.file_field :image, class: 'form-control' %>
          </div>
          <%= button_tag type: :submit, id: 'create-mantra', class: "btn btn-#{current_user.style.create_button}" do %>
            <%= icon('fa fa-plus-circle', 'Create') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='row'>
  <div class='col-md-12 col-sm-12 col-xs-12'>
    <h4>My Mantras</h4>
    <hr style='margin: 0 0 10px 0;'>
    <% current_user.mantras.active.each do |m| %>
      <div class='col-md-4 col-sm-6 col-xs-12 mantra-wrapper'>
        <div class='outer'>
          <div class='inner'>
            <%= link_to m.image.url, target: '_blank' do %>
              <div class='row' style='margin-bottom: 10px;'>
                <%= image_tag m.image.url, class: 'col-md-12 col-sm-12 col-xs-12 mantra-image' %>
              </div>
            <% end if m.image.present? %>
            <div>
              <%= best_in_place m, :title, nil: 'Add a Title', inner_class: 'col-md-12' %>
            </div>
            <div style='margin-top: 5px;'>
              <%= link_to icon('fa fa-trash'), m, method: :delete, class: 'erase', data: { confirm: 'Delete Mantra, you sure?' } %>
              <%= link_to send_now_path(id: m.id), class: 'send-now', method: :post do %>
                <i class='fa fa-spinner fa-spin hidden'></i> Send Now
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end if current_user.mantras.active.present? %>
  </div>
</div>